export { default as Home } from './Home'
export { default as Posts } from './Posts'
export { default as Signup } from './Signup'
export {default as AddPost } from './AddPost'
export { default as SinglePostDetails } from './SinglePostDetails'